version: build-{build}~branch-{branch}

clone_depth: 1

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir win_build
  - cd win_build
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmake -E time cmake . -GNinja -DMYSQL_MAINTAINER_MODE=ERR -DBISON_EXECUTABLE=C:\cygwin64\bin\bison -DWITHOUT_DYNAMIC_PLUGINS=1 -DWITH_UNIT_TESTS=0 -DWITH_MARIABACKUP=0
  - cmake -E time cmake --build .

test_script:
  - set PATH=C:\Strawberry\perl\bin;%PATH%;C:\Program Files (x86)\Windows Kits\10\Debuggers\x64
  - cd %APPVEYOR_BUILD_FOLDER%\win_build\mysql-test
  - set /A parallel=2*%NUMBER_OF_PROCESSORS%
  - perl mysql-test-run.pl --force --max-test-fail=10 --parallel=%parallel% --testcase-timeout=10 --suite=main

image: Visual Studio 2019
